// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// I2S_Rx_naive //
// ------------ //

#define I2S_Rx_naive_wrap_target 4
#define I2S_Rx_naive_wrap 6
#define I2S_Rx_naive_pio_version 0

static const uint16_t I2S_Rx_naive_program_instructions[] = {
    0x20a2, //  0: wait   1 pin, 2
    0x2022, //  1: wait   0 pin, 2
    0x2021, //  2: wait   0 pin, 1
    0x20a1, //  3: wait   1 pin, 1
            //     .wrap_target
    0x2021, //  4: wait   0 pin, 1
    0x20a1, //  5: wait   1 pin, 1
    0x4001, //  6: in     pins, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program I2S_Rx_naive_program = {
    .instructions = I2S_Rx_naive_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = I2S_Rx_naive_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config I2S_Rx_naive_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + I2S_Rx_naive_wrap_target, offset + I2S_Rx_naive_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void I2S_Rx_naive_init(
        PIO pio, uint sm, uint offset,
        uint BCLK_pin, uint WS_pin, uint SD_pin,
        float fs,
        uint WS_frame_size
) {
        // input validation
    assert(BCLK_pin == SD_pin + 1);
    assert(WS_pin == SD_pin + 2);
    const uint cycles_per_edge = 2;
        // get default config
    pio_sm_config c = I2S_Rx_naive_program_get_default_config(offset);
        // set pins
    sm_config_set_in_pins(&c, SD_pin);
    sm_config_set_in_pin_count(&c, 3);
        // set isr and SHIFCTRL_PUSH_THRESH
    sm_config_set_in_shift(&c, false, true, WS_frame_size);
        // pin mask + pindir + pin initialization
    uint64_t pin_mask = (1 << SD_pin) | (1 << WS_pin) | (1 << BCLK_pin);
    uint64_t pindir_mask = (0 << SD_pin) | (0 << WS_pin) | (0 << BCLK_pin);
    pio_sm_set_pindirs_with_mask64(pio, sm, pindir_mask, pin_mask);
    pio_gpio_init(pio, BCLK_pin);
    pio_gpio_init(pio, WS_pin);
    pio_gpio_init(pio, SD_pin);
        // disable input synch on the SD pins
    //pio->input_sync_bypass = 1 << SD_pin;
        // init + enable pio sm
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, false);
}
static inline void I2S_Rx_naive_read(PIO pio, uint sm, 
        uint32_t* lc, uint32_t* rc
) {
    *lc = pio_sm_get_blocking(pio, sm);
    *rc = pio_sm_get_blocking(pio, sm);
}

#endif


