// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// I2S_naive //
// --------- //

#define I2S_naive_wrap_target 2
#define I2S_naive_wrap 9
#define I2S_naive_pio_version 0

static const uint16_t I2S_naive_program_instructions[] = {
    0xf820, //  0: set    x, 0            side 3
    0xa042, //  1: nop                    side 0
            //     .wrap_target
    0x8880, //  2: pull   noblock         side 1
    0x6001, //  3: out    pins, 1         side 0
    0x08e3, //  4: jmp    !osre, 3        side 1
    0x7001, //  5: out    pins, 1         side 2
    0x9880, //  6: pull   noblock         side 3
    0x7001, //  7: out    pins, 1         side 2
    0x18e7, //  8: jmp    !osre, 7        side 3
    0x6001, //  9: out    pins, 1         side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program I2S_naive_program = {
    .instructions = I2S_naive_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = I2S_naive_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config I2S_naive_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + I2S_naive_wrap_target, offset + I2S_naive_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}

#include "hardware/clocks.h"
static inline void I2S_naive_init(
        PIO pio, uint sm, uint offset, 
        uint BCLK_pin, uint WS_pin, uint SD_pin, 
        float fs,
        uint WS_frame_size
) {
        // input validation
    assert(WS_pin == BCLK_pin + 1);
    const uint cycles_per_edge = 2;
        // get default config
    pio_sm_config c = I2S_naive_program_get_default_config(offset);
        // set pins
    sm_config_set_out_pins(&c, SD_pin, 1);
    sm_config_set_sideset_pins(&c, BCLK_pin);
        // set osr shift and SHIFCTRL_PULL_THRESH
    sm_config_set_out_shift(&c, false, false, WS_frame_size-1);
        // set clkdiv
    float clkdiv = clock_get_hz(clk_sys) / (fs * cycles_per_edge * WS_frame_size * 2.0);
    sm_config_set_clkdiv(&c, clkdiv);
        // pin mask + pindir + pin initialization
    uint64_t pin_mask = (1 << SD_pin) | (1 << WS_pin) | (1 << BCLK_pin);
    uint64_t pin_default = (0 << SD_pin) | (1 << WS_pin) | (1 << BCLK_pin);
    pio_sm_set_pins_with_mask64(pio, sm, pin_default, pin_mask);
    pio_sm_set_pindirs_with_mask64(pio, sm, pin_mask, pin_mask);
    pio_gpio_init(pio, BCLK_pin);
    pio_gpio_init(pio, WS_pin);
    pio_gpio_init(pio, SD_pin);
        // init + enable pio sm
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
static inline void I2S_naive_mono_write(PIO pio, uint sm, 
        uint32_t data, uint WS_frame_size
) {
    pio_sm_put_blocking(pio, sm, data << (32 - WS_frame_size));
    pio_sm_put_blocking(pio, sm, data << (32 - WS_frame_size));
}
static inline void I2S_naive_stereo_write(PIO pio, uint sm, 
        uint32_t lc, uint32_t rc, uint WS_frame_size
) {
    pio_sm_put_blocking(pio, sm, lc << (32 - WS_frame_size));
    pio_sm_put_blocking(pio, sm, rc << (32 - WS_frame_size));
}

#endif

